"""Adding data for rate limiting

Revision ID: 05247e191347
Revises: eaf8249b3330
Create Date: 2025-07-04 00:45:39.707524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05247e191347'
down_revision: Union[str, None] = 'eaf8249b3330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crossword_data', sa.Column('percent_filled', sa.Integer(), nullable=False, server_default='100'))
    op.add_column('crossword_data', sa.Column('last_fetched', sa.Date(), nullable=True))
    op.alter_column('crossword_data', 'solve_time',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crossword_data', 'solve_time',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('crossword_data', 'last_fetched')
    op.drop_column('crossword_data', 'percent_filled')
    # ### end Alembic commands ###
