"""Add kind column

Revision ID: 165721f353d1
Revises: 5ba312fa80e2
Create Date: 2025-04-30 00:26:04.752684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '165721f353d1'
down_revision: Union[str, None] = '5ba312fa80e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crossword_data', sa.Column('kind', sa.String(length=20), nullable=False, server_default='daily'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crossword_data', 'kind')
    # ### end Alembic commands ###
