"""Make friend graph undirected

Revision ID: 280b8a4bf14d
Revises: eebb528d8549
Create Date: 2025-11-21 23:18:17.697190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280b8a4bf14d'
down_revision: Union[str, None] = 'eebb528d8549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("""
        DELETE FROM friendships f1
        USING friendships f2
        WHERE f1.node_one = f2.node_two
          AND f1.node_two = f2.node_one
          AND f1.node_one > f1.node_two;
    """)
    op.create_check_constraint('check_node_one_less_than_node_two', 'friendships', 'node_one < node_two')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_node_one_less_than_node_two', 'friendships', type_='check')
    op.execute("""
        INSERT INTO friendships (node_one, node_two)
        SELECT node_two, node_one FROM friendships
        WHERE NOT EXISTS (
            SELECT 1 FROM friendships f2
            WHERE f2.node_one = friendships.node_two AND f2.node_two = friendships.node_one
        );
    """)

    # ### end Alembic commands ###
