"""Remove game and friends relationships

Revision ID: 45317eea4fb8
Revises: b25bdc2a905f
Create Date: 2025-11-21 22:23:26.758785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45317eea4fb8'
down_revision: Union[str, None] = 'b25bdc2a905f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
