"""Change column names

Revision ID: 51c286ccae76
Revises: 45317eea4fb8
Create Date: 2025-11-21 22:27:44.707063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c286ccae76'
down_revision: Union[str, None] = '45317eea4fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # User Adjustments
    op.alter_column('users', 'username', new_column_name='display_name')

    # CrosswordData Adjustments
    op.drop_constraint('unique_user_day', 'crossword_data', type_='unique')
    op.alter_column('crossword_data', 'kind', new_column_name='puzzle_type')
    op.create_unique_constraint('unique_user_day_puzzle_type', 'crossword_data', ['user_id', 'day', 'puzzle_type'])

    # Friendship Adjustments
    op.drop_constraint('friendships_friend_one_fkey', 'friendships', type_='foreignkey')
    op.drop_constraint('friendships_friend_two_fkey', 'friendships', type_='foreignkey')
    op.alter_column('friendships', 'friend_one', new_column_name='node_one')
    op.alter_column('friendships', 'friend_two', new_column_name='node_two')
    op.create_foreign_key('friendships_node_one_fkey', 'friendships', 'users', ['node_one'], ['id'])
    op.create_foreign_key('friendships_node_two_fkey', 'friendships', 'users', ['node_two'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # User Adjustments
    op.alter_column('users', 'display_name', new_column_name='username')

    # CrosswordData Adjustments
    op.drop_constraint('unique_user_day_puzzle_type', 'crossword_data', type_='unique')
    op.alter_column('crossword_data', 'puzzle_type', new_column_name='kind')
    op.create_unique_constraint('unique_user_day', 'crossword_data', ['user_id', 'day', 'kind'])

    # Friendship Adjustments
    op.drop_constraint('friendships_node_one_fkey', 'friendships', type_='foreignkey')
    op.drop_constraint('friendships_node_two_fkey', 'friendships', type_='foreignkey')
    op.alter_column('friendships', 'node_one', new_column_name='friend_one')
    op.alter_column('friendships', 'node_two', new_column_name='friend_two')
    op.create_foreign_key('friendships_friend_one_fkey', 'friendships', 'users', ['friend_one'], ['id'])
    op.create_foreign_key('friendships_friend_two_fkey', 'friendships', 'users', ['friend_two'], ['id'])
    # ### end Alembic commands ###
