"""Incorporate enums

Revision ID: aae6a04c4cca
Revises: 51c286ccae76
Create Date: 2025-11-21 22:41:31.118870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'aae6a04c4cca'
down_revision: Union[str, None] = '51c286ccae76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE crossword_data
        SET status = 'unknown'
        WHERE status = 'incomplete';
    """)
    user_status_enum = postgresql.ENUM('active', 'pending', 'suspended', name='user_status_enum')
    user_status_enum.create(op.get_bind(), checkfirst=True)

    op.execute("ALTER TABLE users ALTER COLUMN account_status DROP DEFAULT")
    op.alter_column('users', 'account_status',
               existing_type=sa.VARCHAR(length=200),
               type_=user_status_enum,
               existing_nullable=False,
               postgresql_using="account_status::user_status_enum",
               existing_server_default=sa.text("'pending'::character varying"))
    op.execute("ALTER TABLE users ALTER COLUMN account_status SET DEFAULT 'pending'")

    solve_status_enum = postgresql.ENUM('complete', 'partial', 'unattempted', 'unknown', name='solve_status_enum')
    solve_status_enum.create(op.get_bind(), checkfirst=True)
    op.execute("ALTER TABLE crossword_data ALTER COLUMN status DROP DEFAULT")
    op.alter_column('crossword_data', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=solve_status_enum,
               postgresql_using="status::solve_status_enum",
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users ALTER COLUMN account_status DROP DEFAULT")
    op.alter_column('users', 'account_status',
               existing_type=sa.Enum('active', 'pending', 'suspended', name='user_status_enum'),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.execute("ALTER TABLE users ALTER COLUMN account_status SET DEFAULT 'pending'")

    user_status_enum = postgresql.ENUM('active', 'pending', 'suspended', name='user_status_enum')
    user_status_enum.drop(op.get_bind(), checkfirst=True)

    op.alter_column('crossword_data', 'status',
               existing_type=sa.Enum('complete', 'partial', 'unattempted', 'unknown', name='solve_status_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    solve_status_enum = postgresql.ENUM('complete', 'partial', 'unattempted', 'unknown', name='solve_status_enum')
    solve_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
