"""Change table names


Revision ID: b25bdc2a905f
Revises: 1482beed588e
Create Date: 2025-11-21 21:11:19.290940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b25bdc2a905f'
down_revision: Union[str, None] = '1482beed588e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('friends_friend_one_fkey', 'friends', type_='foreignkey')
    op.drop_constraint('friends_friend_two_fkey', 'friends', type_='foreignkey')
    op.drop_constraint('crossword_data_user_id_fkey', 'crossword_data', type_='foreignkey')

    op.rename_table('user', 'users')
    op.rename_table('friends', 'friendships')

    # Create new foreign key constraints
    op.create_foreign_key('crossword_data_user_id_fkey', 'crossword_data', 'users', ['user_id'], ['id'])
    op.create_foreign_key('friendships_friend_one_fkey', 'friendships', 'users', ['friend_one'], ['id'])
    op.create_foreign_key('friendships_friend_two_fkey', 'friendships', 'users', ['friend_two'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('crossword_data_user_id_fkey', 'crossword_data', type_='foreignkey')
    op.drop_constraint('friendships_friend_one_fkey', 'friendships', type_='foreignkey')
    op.drop_constraint('friendships_friend_two_fkey', 'friendships', type_='foreignkey')

    op.rename_table('users', 'user')
    op.rename_table('friendships', 'friends')    # ### end Alembic commands ###

    op.create_foreign_key('crossword_data_user_id_fkey', 'crossword_data', 'user', ['user_id'], ['id'])
    op.create_foreign_key('friends_friend_one_fkey', 'friends', 'user', ['friend_one'], ['id'])
    op.create_foreign_key('friends_friend_two_fkey', 'friends', 'user', ['friend_two'], ['id'])