"""Add email verification fields

Revision ID: eaf8249b3330
Revises: 165721f353d1
Create Date: 2025-06-18 20:43:37.853455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf8249b3330'
down_revision: Union[str, None] = '165721f353d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('user', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('account_status', sa.String(length=200), nullable=False, server_default='pending'))
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.add_column('user', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login_at')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'account_status')
    op.drop_column('user', 'email_verified_at')
    op.drop_column('user', 'email_verified')
    # ### end Alembic commands ###
