"""Alter puzzle_type enums

Revision ID: eebb528d8549
Revises: aae6a04c4cca
Create Date: 2025-11-21 23:04:18.672711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'eebb528d8549'
down_revision: Union[str, None] = 'aae6a04c4cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    puzzle_type_enum = postgresql.ENUM('nyt_daily', 'nyt_mini', name='puzzle_type_enum')
    puzzle_type_enum.create(op.get_bind(), checkfirst=True)
    op.execute("""
        UPDATE crossword_data
        SET puzzle_type = 'nyt_daily'
        WHERE puzzle_type = 'daily';
    """)
    op.execute("""
        UPDATE crossword_data
        SET puzzle_type = 'nyt_mini'
        WHERE puzzle_type = 'mini';
    """)
    op.execute("ALTER TABLE crossword_data ALTER COLUMN puzzle_type DROP DEFAULT")
    op.alter_column('crossword_data', 'puzzle_type',
               existing_type=sa.VARCHAR(length=20),
               type_=puzzle_type_enum,
               existing_nullable=False,
               postgresql_using="puzzle_type::puzzle_type_enum",
               existing_server_default=sa.text("'daily'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crossword_data', 'puzzle_type',
               existing_type=sa.Enum('nyt_daily', 'nyt_mini', name='puzzle_type_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'daily'::character varying"))
    op.execute("ALTER TABLE crossword_data ALTER COLUMN puzzle_type SET DEFAULT 'daily'")
    op.execute("""
        UPDATE crossword_data
        SET puzzle_type = 'daily'
        WHERE puzzle_type = 'nyt_daily';
    """)
    op.execute("""
        UPDATE crossword_data
        SET puzzle_type = 'mini'
        WHERE puzzle_type = 'nyt_mini';
    """)
    puzzle_type_enum = postgresql.ENUM('nyt_daily', 'nyt_mini', name='puzzle_type_enum')
    puzzle_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
